version: '3'

services:
  rustua-postgres:
    container_name: rustua-capstone
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: capstone
    command: postgres -c max_wal_size=1GB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

volumes:
  postgres_data:
    driver: local
