application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "rustua"
  password: "rustua"
  database_name: "capstone"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "xxx"
  timeout_milliseconds: 10000
qr_client:
  api_url: "https://api.apilayer.com/short_url/hash"
  api_key: "xxx"
  base_url: "http://127.0.0.1/api/validations"
  base_image_path: "./../qr"
  timeout_milliseconds: 10000
console_cli:
  web_url: "http://127.0.0.1:8000"